// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.APP.Domain;

#nullable disable

namespace Movies.APP.Migrations
{
    [DbContext(typeof(MoviesDb))]
    [Migration("20251119202427_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Movies.APP.Domain.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Christopher",
                            Guid = "cf873ce4-5527-4494-9df6-5dd93574d4f4",
                            IsRetired = false,
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Steven",
                            Guid = "af661299-9c85-4a9a-8b48-dbf4843513ba",
                            IsRetired = false,
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "James",
                            Guid = "ffb1027a-5415-46bc-a534-e35acb3b7169",
                            IsRetired = false,
                            LastName = "Cameron"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Quentin",
                            Guid = "ef611825-04be-4242-824f-3d6e41b99c42",
                            IsRetired = false,
                            LastName = "Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "David",
                            Guid = "e826c69b-6afb-43bc-a131-f158e3097d8e",
                            IsRetired = false,
                            LastName = "Fincher"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Peter",
                            Guid = "4d1f4159-af23-42c4-b14e-5866071aeb9e",
                            IsRetired = false,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Denis",
                            Guid = "c0955c56-cd52-4ec4-b94d-3fde2d2fc432",
                            IsRetired = false,
                            LastName = "Villeneuve"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Jordan",
                            Guid = "a8273e21-daef-4777-97b3-995ba122e5d7",
                            IsRetired = false,
                            LastName = "Peele"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Martin",
                            Guid = "b480cc2f-20a6-4a06-8a4c-50afe5fdf81e",
                            IsRetired = false,
                            LastName = "Scorsese"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Ridley",
                            Guid = "b8ca1786-f076-4d33-acad-dd0808daaa89",
                            IsRetired = false,
                            LastName = "Scott"
                        });
                });

            modelBuilder.Entity("Movies.APP.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = "b4b0ed87-5195-4d75-a76e-59598d590555",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Guid = "5238fe8a-84f0-4a9c-8fe5-d96b0f699e5e",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Guid = "f1e6f6c5-46ed-4bda-85ad-30fbdfbef2a3",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 4,
                            Guid = "c710ec12-31aa-4102-a8a5-c7a08e95ed9a",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Guid = "317c96b6-a3f0-4c83-80f4-4da6fc76ef34",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 6,
                            Guid = "cd32223e-2f9f-4a9f-aef6-bf65ff57a226",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Guid = "d2b20344-03b5-4605-b2eb-7e6f0f29af02",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Guid = "986e452d-cfcc-47eb-996f-342f85c827f2",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 9,
                            Guid = "cf02985a-b6b2-4641-bc1d-27aa7565b8ff",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Guid = "149edf5d-6eb1-4b0e-a95a-220fb18afcbd",
                            Name = "Crime"
                        });
                });

            modelBuilder.Entity("Movies.APP.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            Guid = "cf1353b4-5e86-4336-b9b7-3ec4d64f8765",
                            Name = "Inception",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 829000000m
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 1,
                            Guid = "8a87e06c-6a51-45f4-ab40-db658cfc357f",
                            Name = "Interstellar",
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 677000000m
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 3,
                            Guid = "d7348dd2-21d8-430e-a3db-31303499a6f7",
                            Name = "Avatar",
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 2923000000m
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 4,
                            Guid = "d561b1de-9163-4964-a58a-eda32e4c0ac1",
                            Name = "Pulp Fiction",
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 214000000m
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 5,
                            Guid = "220c718d-4058-42c6-a7a0-a5c17bb3a9fb",
                            Name = "Fight Club",
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 101000000m
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 6,
                            Guid = "623cc0e4-ae12-4049-b90f-220d97b31001",
                            Name = "LOTR: Fellowship",
                            ReleaseDate = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 880000000m
                        },
                        new
                        {
                            Id = 7,
                            DirectorId = 8,
                            Guid = "349c03d4-4fa3-459a-acd7-2c34f50327f7",
                            Name = "Get Out",
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 255000000m
                        },
                        new
                        {
                            Id = 8,
                            DirectorId = 9,
                            Guid = "84a6e440-9a91-4567-9ffb-7146eba94f8e",
                            Name = "Shutter Island",
                            ReleaseDate = new DateTime(2010, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 295000000m
                        },
                        new
                        {
                            Id = 9,
                            DirectorId = 10,
                            Guid = "86d5e0fc-f897-4178-bfd4-bfd20f39562a",
                            Name = "Gladiator",
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 503000000m
                        },
                        new
                        {
                            Id = 10,
                            DirectorId = 2,
                            Guid = "6406205b-a498-4949-b5db-1a7ed3822278",
                            Name = "Jurassic Park",
                            ReleaseDate = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRevenue = 1030000000m
                        });
                });

            modelBuilder.Entity("Movies.APP.Domain.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId", "GenreId")
                        .IsUnique();

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Guid = "3d811993-e4dc-417d-a715-096fa32f5a14",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 3,
                            Guid = "8364c9d0-5227-455e-9bdf-f5a956059010",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            Guid = "d1a72790-bb00-4477-acb2-a784a41598ce",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 2,
                            Guid = "57635c5f-b22e-464c-bc67-296e7864229c",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 1,
                            Guid = "7e533623-1f6d-499e-a114-a51619dfba3a",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 5,
                            Guid = "94efa5d6-78a6-49eb-ae60-a74b39ed8729",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 10,
                            Guid = "ceae109a-5052-4c35-8c87-9836ac342cf9",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 10,
                            Guid = "3dd6617d-561b-4e66-8e18-7deeeed0f09b",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 3,
                            Guid = "4e0838a7-e03f-4da6-8938-a976f17efdff",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 6,
                            Guid = "51839dde-a059-44d6-8d57-1c82b90c1792",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 4,
                            Guid = "fe512a0e-757a-4f49-8b09-ad05742a35cb",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 9,
                            Guid = "e84e457c-aa82-4766-859f-76ee7f580e1d",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 7,
                            Guid = "c536c4af-1c17-43f6-a26c-13c10a43d769",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 5,
                            Guid = "2218269a-70a3-4202-8000-bc7f0d8cade3",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 4,
                            Guid = "30c38a23-acd0-442f-b27b-a5f252b6fc19",
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("Movies.APP.Domain.Movie", b =>
                {
                    b.HasOne("Movies.APP.Domain.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Movies.APP.Domain.MovieGenre", b =>
                {
                    b.HasOne("Movies.APP.Domain.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Movies.APP.Domain.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movies.APP.Domain.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Movies.APP.Domain.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Movies.APP.Domain.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
